In [2]:
import pandas as pd
pd.__version__

'2.2.3'

In [4]:
lst = ['indore','mumbai','jaipur']
sr=pd.Series(lst)
print(type(sr))
print(sr)

<class 'pandas.core.series.Series'>
0    indore
1    mumbai
2    jaipur
dtype: object

In [5]:
num=[1,2,3,4,5,6,7]
sri=pd.Series(num)
print(type(sri))
print(sri)

<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [11]:
dict={0:'tum',1:'mere',2:'rohit'}
sri1=pd.Series(dict)
print(type(sri1))
print(sri1)

<class 'pandas.core.series.Series'>
0      tum
1     mere
2    rohit
dtype: object

In [14]:
dict1={0:'tum','ram':'mere',2:20,20.3:20}
sri2=pd.Series(dict1)
print(type(sri2))
print(sri2)

<class 'pandas.core.series.Series'>
0        tum
ram     mere
2         20
20.3      20
dtype: object

In [17]:
dict1={0:'tum','ram':'mere',2:20,20.3:20}
sri2=pd.Series(data=dict1,index=[0,'ram',2,20.3])
print(type(sri2))
print(sri2)

<class 'pandas.core.series.Series'>
0        tum
ram     mere
2         20
20.3      20
dtype: object

In [ ]:
list1=[1,2,3,4,5]
ser=pd.Series(list1,copy=False)
ser.iloc[0]=909

In [20]:
import numpy as np
arr=np.array([1,2,3,4])
ser1=pd.Series(arr,copy=False)
ser1.iloc[0]=1919
print(ser1)

0    1919
1       2
2       3
3       4
dtype: int64

In [22]:
dict1={0:'tum','ram':'mere',2:20,20.3:20}
sri2=pd.Series(data=dict1)
print(type(sri2))
print(sri2)

<class 'pandas.core.series.Series'>
0        tum
ram     mere
2         20
20.3      20
dtype: object

In [23]:
name=['rohit','karan','yash']
sries=pd.Series(data=name,index=['r','k','y'])
print(sries)

r    rohit
k    karan
y     yash
dtype: object

In [27]:
## dtype paramenters
num1=[10,30,20,50,40,0]
ser=pd.Series(data=num1,dtype=bool)
print(ser)

0     True
1     True
2     True
3     True
4     True
5    False
dtype: bool

In [28]:
num2=[10,30,20,50,40,0]
ser=pd.Series(data=num2,name='my number')
print(ser.name)
print(ser)

my number
0    10
1    30
2    20
3    50
4    40
5     0
Name: my number, dtype: int64

In [43]:
stri=['abcdefghijklmnopqrstuvwxyz']
sr=pd.Series(data=stri)
print(sr[0][3])

d

In [49]:
alp=list('abcdefghijklmnopqrstuvwxyz')
s=pd.Series(data=alp,index=alp)
# s=s.add_prefix('lable_')
s=s.add_suffix('_lable')
# print(s)
s.get(0)
s.get('9')

C:\Users\himan\AppData\Local\Temp\ipykernel_7208\3352218236.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s.get(0)

In [4]:
## Boolean masking for Condition Based Selection.
s=pd.Series([1,2,3,4,5])
print(s[[True,False,True,False,True]])
print(s.loc[[True,False,True,False,True]])
print(s.iloc[[True,False,True,False,True]])
print(s.get([[True,False,True,False,True]]))

0    1
2    3
4    5
dtype: int64
0    1
2    3
4    5
dtype: int64
0    1
2    3
4    5
dtype: int64
None

In [10]:
## USing of collables in selection 
s=pd.Series([i for i in range(20)])
def odd_selection(s):
    return[True if i%2!=0 else False for i in range(s.size)]
    
print(s[odd_selection])
print(s)

1      1
3      3
5      5
7      7
9      9
11    11
13    13
15    15
17    17
19    19
dtype: int64
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int64

In [19]:
s=pd.Series([i for i in range(100)])
def odd_selection(s):
    return[True if i%7==0 else False for i in range(s.size)]
    
print(s[odd_selection])

0      0
7      7
14    14
21    21
28    28
35    35
42    42
49    49
56    56
63    63
70    70
77    77
84    84
91    91
98    98
dtype: int64

In [24]:
arr=[1000,2000,3000,4000]
s=pd.Series(data=arr,index=['sunny','raju','rohit','karan'])
print(lambda s:[True if sal>=2500 and sal<=5000 else False for sal in s])

<function <lambda> at 0x000002437438C2C0>

In [29]:
df =pd.read_csv('SemEval2018-T3_gold_test_taskA_emoji.txt',sep='\t')
df

     Tweet index  Label                                         Tweet text
0              1      0  @Callisto1947 Can U Help?||More conservatives ...
1              2      1  Just walked in to #Starbucks and asked for a "...
2              3      0              #NOT GONNA WIN http://t.co/Mc9ebqjAqj
3              4      0  @mickymantell He is exactly that sort of perso...
4              5      1  So much #sarcasm at work mate 10/10 #boring 10...
..           ...    ...                                                ...
779          780      0  If you drag yesterday into today, your tomorro...
780          781      0  Congrats to my fav @JennyBrew & her team & my ...
781          782      0  @allkpop: Jessica sheds tears at her fan signi...
782          783      1  #Irony: al jazeera is pro Anti - #GamerGate be...
783          784      0  #NOT ALL 👌 There good & bad in every occupatio...

[784 rows x 3 columns]

In [30]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [31]:
df.head()

   Tweet index  Label                                         Tweet text
0            1      0  @Callisto1947 Can U Help?||More conservatives ...
1            2      1  Just walked in to #Starbucks and asked for a "...
2            3      0              #NOT GONNA WIN http://t.co/Mc9ebqjAqj
3            4      0  @mickymantell He is exactly that sort of perso...
4            5      1  So much #sarcasm at work mate 10/10 #boring 10...

In [32]:
df.count()

Tweet index    784
Label          784
Tweet text     784
dtype: int64

In [38]:
df.notnull()

     Tweet index  Label  Tweet text
0           True   True        True
1           True   True        True
2           True   True        True
3           True   True        True
4           True   True        True
..           ...    ...         ...
779         True   True        True
780         True   True        True
781         True   True        True
782         True   True        True
783         True   True        True

[784 rows x 3 columns]

In [39]:
df.min()

Tweet index                                                    1
Label                                                          0
Tweet text     #A #tax #per mile? #Americans #should #not #al...
dtype: object

In [40]:
df.max()

Tweet index                                                  784
Label                                                          1
Tweet text     ❓❓GOT MENTIONS ❓❓||#MGWV #AutoFollow #RETWEET ...
dtype: object

In [43]:
df.median

<bound method DataFrame.median of      Tweet index  Label                                         Tweet text
0              1      0  @Callisto1947 Can U Help?||More conservatives ...
1              2      1  Just walked in to #Starbucks and asked for a "...
2              3      0              #NOT GONNA WIN http://t.co/Mc9ebqjAqj
3              4      0  @mickymantell He is exactly that sort of perso...
4              5      1  So much #sarcasm at work mate 10/10 #boring 10...
..           ...    ...                                                ...
779          780      0  If you drag yesterday into today, your tomorro...
780          781      0  Congrats to my fav @JennyBrew & her team & my ...
781          782      0  @allkpop: Jessica sheds tears at her fan signi...
782          783      1  #Irony: al jazeera is pro Anti - #GamerGate be...
783          784      0  #NOT ALL 👌 There good & bad in every occupatio...

[784 rows x 3 columns]>

In [46]:
df.mode()

     Tweet index  Label                                         Tweet text
0              1    0.0  #A #tax #per mile? #Americans #should #not #al...
1              2    NaN  #AdvancedWarfare is so much better than any FP...
2              3    NaN  #Alien dit : What is #Religion, it is a cultur...
3              4    NaN  #Analysis -- #Economic #issues #whip #up #Isra...
4              5    NaN  #AskSuperwomanLIVE if you could swim in any li...
..           ...    ...                                                ...
779          780    NaN  work Wednesday-Sunday .. #yay #not #moneytho 😩😭💰😒
780          781    NaN  you believe you can say something, provide no ...
781          782    NaN  you seem super smart MT "@GrannyMarried: @Docj...
782          783    NaN  ~I'm not closed-minded, I'm just dogmatic~ #sa...
783          784    NaN  ❓❓GOT MENTIONS ❓❓||#MGWV #AutoFollow #RETWEET ...

[784 rows x 3 columns]

In [48]:
s1= pd.Series(data=[10,20,30,40],index=['a','b','c','d'])
s2= pd.Series(data=[50,60,70,80],index=['c','d','e','f'])
print(s1.sub(s2))
print(s1.sub(s2,fill_value=0))
print(s1.mul(s2))
print(s1.mul(s2,fill_value=0))
print(s1.div(s2))
print(s1.div(s2,fill_value=0))

a     NaN
b     NaN
c   -20.0
d   -20.0
e     NaN
f     NaN
dtype: float64
a    10.0
b    20.0
c   -20.0
d   -20.0
e   -70.0
f   -80.0
dtype: float64
a       NaN
b       NaN
c    1500.0
d    2400.0
e       NaN
f       NaN
dtype: float64
a       0.0
b       0.0
c    1500.0
d    2400.0
e       0.0
f       0.0
dtype: float64
a         NaN
b         NaN
c    0.600000
d    0.666667
e         NaN
f         NaN
dtype: float64
a         inf
b         inf
c    0.600000
d    0.666667
e    0.000000
f    0.000000
dtype: float64